add box functions

diff --git a/lib/box_functions b/lib/box_functions
--- a/lib/box_functions
+++ b/lib/box_functions
@@ -21,9 +21,9 @@ COL_CYAN=$ESC_SEQ"36;01m"
 function banner() {
   clear
   info '
-               _                      _       
-  ___ ___   __| | ___ _ __ ___  _ __ (_)_ __  
- / __/ _ \ / _  |/ _ \  __/ _ \|  _ \| |  _ \ 
+               _                      _
+  ___ ___   __| | ___ _ __ ___  _ __ (_)_ __
+ / __/ _ \ / _  |/ _ \  __/ _ \|  _ \| |  _ \
 | (_| (_) | (_| |  __/ | | (_) | | | | | | | |
  \___\___/ \__,_|\___|_|  \___/|_| |_|_|_| |_|
 '
@@ -48,81 +48,109 @@ function error() { echo -e "$COL_RED $1 $COL_RESET "; }
 
 function die() { echo "$@" 1>&2 ; exit 1; }
 
-function require_cask() {
-    running "brew cask $1"
-    brew cask list "$1" > /dev/null 2>&1 | true
-    if [[ ${PIPESTATUS[0]} != 0 ]]; then
-        action "brew cask install $1"
-        brew cask install $1
-        if [[ $? != 0 ]]; then
-            error "failed to install $1! aborting..."
-            exit -1
-        fi
-    fi
-    ok
+function sourceNVM(){
+  export NVM_DIR=~/.nvm
+  source $NVM_DIR/nvm.sh
+}
+
+function require_apm() {
+  running "checking atom plugin: $1"
+  apm list --installed --bare | grep $1@ > /dev/null
+  if [[ $? != 0 ]]; then
+    action "apm install $1"
+    apm install $1
+  fi
+  ok
 }
 
 function require_brew() {
-    running "brew $1 $2"
-    brew list "$1" > /dev/null 2>&1 | true
-    if [[ ${PIPESTATUS[0]} != 0 ]]; then
-        action "brew install $1 $2"
-        brew install $1 $2
-        if [[ $? != 0 ]]; then
-            error "failed to install $1! aborting..."
-            exit -1
-        fi
+  running "brew $1 $2"
+  brew list "$1" > /dev/null 2>&1 | true
+  if [[ ${PIPESTATUS[0]} != 0 ]]; then
+    action "brew install $1 $2"
+    brew install $1 $2
+    if [[ $? != 0 ]]; then
+      error "failed to install $1! aborting..."
+      exit -1
     fi
-    ok
+  fi
+  ok
+}
+
+function require_cask() {
+  running "brew cask $1"
+  brew cask list "$1" > /dev/null 2>&1 | true
+  if [[ ${PIPESTATUS[0]} != 0 ]]; then
+    action "brew cask install $1"
+    brew cask install $1
+    if [[ $? != 0 ]]; then
+      error "failed to install $1! aborting..."
+      exit -1
+    fi
+  fi
+  ok
 }
 
 function require_gem() {
-    running "gem $1"
-    if [[ $(gem list --local | grep "$1" | head -1 | cut -d' ' -f1) != "$1" ]];
-        then
-            action "gem install $1"
-            gem install $1
-    fi
-    ok
+  running "gem $1"
+  if [[ $(gem list --local | grep "$1" | head -1 | cut -d' ' -f1) != "$1" ]]; then
+    action "gem install $1"
+    gem install $1
+  fi
+  ok
 }
 
 function require_npm() {
-    npmlist=$(npm list -g)
-    running "npm $1"
-    echo "$npmlist" | grep "$1"@ > /dev/null
-    if [[ $? != 0 ]]; then
-        action "npm install -g $1"
-        npm install -g $1
-    fi
-    ok
+  npmlist=$(npm list -g)
+  running "npm $1"
+  echo "$npmlist" | grep "$1"@ > /dev/null
+  if [[ $? != 0 ]]; then
+    action "npm install -g $1"
+    npm install -g $1
+  fi
+  ok
+}
+
+function require_nvm() {
+  mkdir -p ~/.nvm
+  cp $(brew --prefix nvm)/nvm-exec ~/.nvm/
+  sourceNVM
+  nvm install $1
+  if [[ $? != 0 ]]; then
+    action "installing nvm"
+    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.25.4/install.sh | bash
+    . ~/.bashrc
+    nvm install $1
+  fi
+  nvm use $1
+  ok
 }
 
 function require_vagrant_plugin() {
-    running "vagrant plugin $1"
-    local vagrant_plugin="$1"
-    local vagrant_plugin_version="$2"
-    local grepExpect=$vagrant_plugin
-    local grepStatus=$(vagrant plugin list | grep "$vagrant_plugin")
+  running "vagrant plugin $1"
+  local vagrant_plugin="$1"
+  local vagrant_plugin_version="$2"
+  local grepExpect=$vagrant_plugin
+  local grepStatus=$(vagrant plugin list | grep "$vagrant_plugin")
 
+  if [[ ! -z "$vagrant_plugin_version" ]]; then
+    grepExpect=$grepExpect' ('$vagrant_plugin_version')'
+  else
+    # we are only looking for the name
+    grepStatus=${grepStatus%% *}
+  fi
+
+  #echo 'checking if '$grepExpect' is installed via grepStatus: '$grepStatus
+
+  if [[ "$grepStatus" != "$grepExpect" ]]; then
+    action "installing vagrant plugin $1 $2"
     if [[ ! -z "$vagrant_plugin_version" ]]; then
-        grepExpect=$grepExpect' ('$vagrant_plugin_version')'
+      vagrant plugin install "$vagrant_plugin" --plugin-version "$vagrant_plugin_version"
     else
-        # we are only looking for the name
-        grepStatus=${grepStatus%% *}
+      vagrant plugin install "$vagrant_plugin"
     fi
-
-    #echo 'checking if '$grepExpect' is installed via grepStatus: '$grepStatus
-
-    if [[ "$grepStatus" != "$grepExpect" ]];
-        then
-            action "installing vagrant plugin $1 $2"
-            if [[ ! -z "$vagrant_plugin_version" ]]; then
-                vagrant plugin install "$vagrant_plugin" --plugin-version "$vagrant_plugin_version"
-            else
-                vagrant plugin install "$vagrant_plugin"
-            fi
-    fi
-    ok
+  fi
+  ok
 }
 
 function git_clone_or_update() {
@@ -164,6 +192,27 @@ function profile_write {
     echo "$1" >> "$2"
   fi
   ok
+}
+
+function symlinkifne {
+  running "$1"
+
+  if [[ -e $1 ]]; then
+    # file exists
+    if [[ -L $1 ]]; then
+      # it's already a simlink (could have come from this project)
+      echo -en '\tsimlink exists, skipped\t';ok
+      return
+    fi
+    # backup file does not exist yet
+    if [[ ! -e ~/.dotfiles_backup/$1 ]];then
+      mv $1 ~/.dotfiles_backup/
+      echo -en 'backed up saved...';
+    fi
+  fi
+  # create the link
+  ln -s ~/.dotfiles/$1 $1
+  echo -en '\tlinked';ok
 }
 
 TEMPLATE='#!/usr/bin/env bash
